# Currently name is only used to create a unique path on /vftmp/
name: greatlakes
forecasts:
 # first_year: 1993
 first_year: 2022
  last_year: 2022
  months:
    - 3
    - 6
    - 9
    - 12
  ensemble_size: 10

# Name the snapshot files to look for in the history tar files.
# These are monthly instantaneous data that will be used for initial conditions.
# "_snap" is appended to these names, so the below says to look for files
# named ocean_month_snap, ice_month_snap, and ocean_cobalt_tracers_snap.
snapshots:
  - ocean_month
  - ice_month
  
# Use forecasts initialized between these dates (inclusive) to
# calculate the lead-dependent climatologies.
climatology:
  first_year: 1993
  last_year: 2019

# Configure the model bounding box, grid files, and open boundaries
domain:
  south_lat: 40
  north_lat: 50
  west_lon: -100
  east_lon: -65

filesystem:
  # Where to put data that will be used to force the model:
  forecast_input_data: /work/pja/mom6/forecast_input_data/spear_med
  # Where to put results from the model simulations:
  forecast_output_data: /work/pja/mom6/forecast_output_data
  # Where to put the model input on Gaea:
  gaea_input_data: /gpfs/f6/ira-cefi/scratch/Peter.Alsip/MOM_INPUT/lakes/forecast_input_data/spear_med
  # Path to existing daily river files (one file per year, padded):
 # yearly_river_files: /work/acr/mom6/nwa12/glofas/glofas_runoff_{year}.nc
  # Path to existing open boundary condition data:
 # open_boundary_files: /work/acr/mom6/nwa12/glorys/updated
  # Path to monthly averaged temperature and salinity data, will be used for nudging:
 # monthly_data_nudging: /work/acr/glorys/monthly_filled/glorys_monthly_ts_fine_{year}.nc
  # Path to ocean_static file without mask table:
 # ocean_static: /home/Andrew.C.Ross/git/nwa12/data/geography/ocean_static.nc
  # Path to the nudged analysis simulation that will be used for initial conditions:
 # analysis_history: /archive/acr/fre/NWA/2024_04_update/NWA12_physics_2024_04_nudgets-90d/gfdl.ncrc5-intel22-prod/history
  # Path to model output from individual forecast simulations:
 # forecast_history: /archive/acr/fre/NWA/2024_04_update/NWA12_forecast_2024_04_{year}-{month:02d}-e{ensemble:02d}/gfdl.ncrc5-intel22-prod/history/
  # TODO:need to have process_spear_job.sh read the path to place processed SPEAR data from here
